### ISSUE TITLE
Location tags not added in location import updates

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/openmrs-module-dhislocation#7]
Location tags are not added in subsequent updates to a location in OMRS. 

Steps to replicate:
1. Create a location in DHIS2 (do not assign org unit group in DHIS2)
2. Import to OMRS
3. Go back to DHIS2 and add the location to an org unit group
4. Re-import to OMRS

The org unit group that was added to the location in DHIS2 should appear as the location tag for the location in OMRS, but it does not.

**Comment by maimoonak** [comment]
To make sure that all locations are not updated again and again and audit data retains a meaningful information, module doesnot import location which have not been updated after last sync. DHIS assigns locations to organizationUnitGroups not the other way around. i.e. location is not updated with new group which leads to lastUpdate property showing date in past. This led to OpenMRS skipping such locations while importing data. The issue has been fixed by comparing Location Tags separately in release 1.1.0b.

**Comment by cafootitt** [comment]
Lgtm. Location tags are added on subsequent import.
